# Generated by Django 6.0.8 on 2026-08-04 18:12

from decimal import Decimal

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapaCanal',
            fields=[
                ('codigo_vendedor', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='codigo do vendedor')),
                ('canal', models.CharField(choices=[('Marketplace', 'Marketplace'), ('Venda interna', 'Venda interna'), ('Balcao-PDV', 'Balcao / PDV'), ('(pedido sem cadastro)', 'Pedido sem cadastro')], max_length=30, verbose_name='canal')),
                ('observacao', models.CharField(blank=True, max_length=200, verbose_name='observacao')),
            ],
            options={
                'verbose_name': 'mapa de canal',
                'verbose_name_plural': 'mapa de canais',
                'ordering': ['codigo_vendedor'],
            },
        ),
        migrations.CreateModel(
            name='MapaGrupo',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='codigo')),
                ('rotulo', models.CharField(max_length=80, verbose_name='rotulo')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'grupo',
                'verbose_name_plural': 'grupos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ParamOutlier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite', models.DecimalField(decimal_places=4, default=Decimal('-1.0'), help_text='Margem percentual minima aceita. -1.0 = custo maior que o dobro do preco.', max_digits=6, verbose_name='limite de margem')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'parametro de outlier',
                'verbose_name_plural': 'parametro de outlier',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ExecucaoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(max_length=10, verbose_name='arquivo')),
                ('competencia', models.DateField(blank=True, null=True, verbose_name='competencia')),
                ('dt_carga', models.DateField(verbose_name='data da carga')),
                ('linhas_lidas', models.IntegerField(default=0, verbose_name='linhas lidas')),
                ('linhas_gravadas', models.IntegerField(default=0, verbose_name='linhas gravadas')),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('erro', 'Erro')], max_length=10)),
                ('mensagem', models.TextField(blank=True, verbose_name='mensagem')),
                ('caminho_parquet', models.CharField(blank=True, max_length=300, verbose_name='parquet')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'execucao de carga',
                'verbose_name_plural': 'execucoes de carga',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['arquivo', '-criado_em'], name='core_execuc_arquivo_4a9950_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReclassificacaoSKU',
            fields=[
                ('sku', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='SKU')),
                ('observacao', models.CharField(blank=True, max_length=200, verbose_name='observacao')),
                ('classificado_em', models.DateTimeField(auto_now=True)),
                ('classificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.mapagrupo', verbose_name='grupo')),
            ],
            options={
                'verbose_name': 'reclassificacao de SKU',
                'verbose_name_plural': 'reclassificacoes de SKU',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='codigo')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(blank=True, help_text="Vinculo que define o que o perfil 'vendedor' enxerga.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendedor', to=settings.AUTH_USER_MODEL, verbose_name='usuario do BI')),
            ],
            options={
                'verbose_name': 'vendedor',
                'verbose_name_plural': 'vendedores',
                'ordering': ['nome'],
            },
        ),
    ]
