# Generated by Django 6.0.8 on 2026-08-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_escopo_nas_agregadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='protegido',
            field=models.BooleanField(default=False, help_text='Conta administrativa de emergencia. Nao pode ser alterada nem removida pela interface — so por acesso direto ao banco.', verbose_name='protegido'),
        ),
    ]
